version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8001:5432"
    environment:
      POSTGRES_USER: vikram
      POSTGRES_PASSWORD: vikram9890
      POSTGRES_DB: social_media

volumes:
    postgres_data:
